/*
 * MIT License
 *
 * Copyright (c) 2026 Lovecast Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
import { describe, expect, it } from 'vitest';
import { isCompactContinuationUserTurnText, isKnownHarnessInjectedUserTurnText } from "../harness-injected-user-turns.js";
describe('isKnownHarnessInjectedUserTurnText', ()=>{
    it('matches every known harness tag, including attribute-carrying forms', ()=>{
        const injected = [
            '<task-notification> <task-id>bzthj2b8r</task-id> <tool-use-id>toolu_01abc</tool-use-id>',
            '<task-notification summary="Agent finished">',
            '<system-reminder>context</system-reminder>',
            '<agent-message from="reviewer-A-r3b"> REVIEW the diff',
            '<teammate-message teammate_id="worker-1">status?',
            '<cross-session-message from="other session">hello',
            '<channel source="general">new post',
            '<fork-boilerplate>Your directive: ship it',
            '<user-memory-input>remember this',
            '<mcp-resource-update uri="db://x">',
            '<mcp-polling-update>tick',
            '<command-name>/review</command-name>',
            '<command-message>review</command-message>',
            '<command-args>--fix</command-args>',
            '<local-command-stdout>ok</local-command-stdout>',
            '<local-command-stderr>boom</local-command-stderr>',
            '<local-command-caveat>Caveat: tool output</local-command-caveat>',
            '<bash-input>ls</bash-input>',
            '<bash-stdout>file.txt</bash-stdout>',
            '<bash-stderr>err</bash-stderr>',
            '<user-prompt-submit-hook>hook context</user-prompt-submit-hook>'
        ];
        for (const text of injected){
            expect(isKnownHarnessInjectedUserTurnText(text), text).toBe(true);
        }
    });
    it('matches harness prose wrappers and notices', ()=>{
        expect(isKnownHarnessInjectedUserTurnText('A message arrived from teammate-b:\n<agent-message>hi')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('Another Claude session sent a message:\n<agent-message>hi')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('No response requested.')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('[Request interrupted by user]')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('[Request interrupted by user for tool use]')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('This session is being continued from a previous conversation.')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('Caveat: the messages below were generated by the user while running local commands.')).toBe(true);
    });
    it('distinguishes compact continuation from other harness turns', ()=>{
        expect(isCompactContinuationUserTurnText('This session is being continued from a previous conversation. Summary follows.')).toBe(true);
        expect(isCompactContinuationUserTurnText('<task-notification>done')).toBe(false);
        expect(isCompactContinuationUserTurnText('<command-name>/review</command-name>')).toBe(false);
    });
    it('is case-insensitive and ignores surrounding whitespace', ()=>{
        expect(isKnownHarnessInjectedUserTurnText('  <TASK-NOTIFICATION> done')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('\n<System-Reminder> hi')).toBe(true);
    });
    it('keeps real user prompts, including ones that mention the tags', ()=>{
        expect(isKnownHarnessInjectedUserTurnText('fix the login bug')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('why does <task-notification> show in the sidebar?')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('   ')).toBe(false);
    });
    it('classifies from a bounded head so multi-KB pastes stay cheap', ()=>{
        const largePrompt = `<task-notification>done</task-notification>\n${'x'.repeat(20_000)}`;
        expect(isKnownHarnessInjectedUserTurnText(largePrompt)).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText(`fix login ${'y'.repeat(20_000)}`)).toBe(false);
    });
    it('keeps single-word tag pastes, custom elements, and underscore wrappers', ()=>{
        expect(isKnownHarnessInjectedUserTurnText('<user_query>fix the bug</user_query>')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('<div class="x">pasted html</div>')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('<script>alert(1)</script> — why is this flagged?')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('<https://example.com/a-b> what is this?')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('<foo-bar@example.com> sent me this')).toBe(false);
    });
    it('does not treat unknown kebab tags as machinery', ()=>{
        expect(isKnownHarnessInjectedUserTurnText('<my-custom-element>pasted code')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('<brand-new-harness-tag id="1">payload')).toBe(false);
        expect(isKnownHarnessInjectedUserTurnText('<queued-notice>\nlater')).toBe(false);
    });
    it('only treats the attributed <channel source=…> form as machinery', ()=>{
        expect(isKnownHarnessInjectedUserTurnText('<channel source="general">new post')).toBe(true);
        expect(isKnownHarnessInjectedUserTurnText('<channel>general</channel> explain this feed element')).toBe(false);
    });
});
