/*
 * MIT License
 *
 * Copyright (c) 2026 Lovecast Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
import { describe, expect, it } from 'vitest';
import { isNoiseMessage, stripNoiseMessages } from "../native-chat-noise.js";
function msg(role, text, blocks) {
    return {
        id: text.slice(0, 8),
        role,
        blocks: blocks ?? [
            {
                type: 'text',
                text
            }
        ],
        timestamp: 0,
        source: 'transcript'
    };
}
describe('isNoiseMessage', ()=>{
    it('flags task-notification and system-reminder user turns', ()=>{
        expect(isNoiseMessage(msg('user', '<task-notification>\n<task-id>x</task-id>'))).toBe(true);
        expect(isNoiseMessage(msg('user', '<system-reminder>\nbe careful'))).toBe(true);
        expect(isNoiseMessage(msg('user', 'Caveat: The messages below were generated by the user while running local commands'))).toBe(true);
        expect(isNoiseMessage(msg('user', '[Request interrupted by user]'))).toBe(true);
    });
    it('keeps real user messages', ()=>{
        expect(isNoiseMessage(msg('user', 'make it work for codex'))).toBe(false);
        expect(isNoiseMessage(msg('user', '<my-custom-element>pasted code'))).toBe(false);
    });
    it('keeps assistant and tool turns', ()=>{
        expect(isNoiseMessage(msg('assistant', '<system-reminder> in prose'))).toBe(false);
        expect(isNoiseMessage(msg('system', 'Conversation interrupted'))).toBe(false);
    });
    it('keeps a user turn that carries tool results', ()=>{
        expect(isNoiseMessage(msg('user', '', [
            {
                type: 'tool-result',
                output: 'ok'
            }
        ]))).toBe(false);
    });
    it('stripNoiseMessages removes only the noise', ()=>{
        const out = stripNoiseMessages([
            msg('user', 'hello'),
            msg('user', '<task-notification>done'),
            msg('assistant', 'hi')
        ]);
        expect(out.map((m)=>m.role)).toEqual([
            'user',
            'assistant'
        ]);
    });
});
